In [1]:
import numpy as np

## Numpy Array

In [4]:
myList = [20,30,40]

In [5]:
type(myList)

list

In [7]:
np.array(myList)

array([20, 30, 40])

In [8]:
matrixList= [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
matrixList[1][0]

20

In [10]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Arange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Zeros

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace

In [20]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

## Eye

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [28]:
np.random.randn(2)

array([-1.10095375,  0.28369986])

In [34]:
np.random.randint(1,100)

83

In [35]:
np.random.randint(1,300,5)

array([ 84, 122, 271, 143,   1])

In [36]:
myNumpyArray= np.arange(30)

In [37]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [46]:
myRandomArray= np.random.randint(1,100,15)

In [47]:
myRandomArray

array([ 6, 86,  2, 63, 73, 99, 85, 82, 52, 32, 61, 98, 35, 82, 14])

## Numpy Array Methods

In [48]:
myNumpyArray.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [49]:
myNumpyArray.max()

29

In [50]:
myRandomArray.max()

99

In [51]:
myRandomArray.min()

2

In [54]:
myRandomArray.argmax()

5

In [55]:
myRandomArray.argmin()

2

In [56]:
myNumpyArray.shape

(30,)

In [57]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [58]:
reshapeMyArray= myNumpyArray.reshape(5,6)

In [59]:
reshapeMyArray.shape

(5, 6)

## İndex

In [60]:
myArray = np.arange(0,15)

In [61]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
myArray[5]

5

In [63]:
myArray[3:8]

array([3, 4, 5, 6, 7])

In [64]:
myArray[3:8]=-5

In [65]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [66]:
anotherArray = np.arange(0,24)

In [67]:
anotherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [68]:
slicingArray= anotherArray[4:9]

In [69]:
slicingArray

array([4, 5, 6, 7, 8])

In [70]:
anotherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
slicingArray[:] = 700

In [72]:
slicingArray

array([700, 700, 700, 700, 700])

In [73]:
anotherArray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

Numpy dizilerinde dizi içerisinden aldığınız bir parçayı işlediğinizde asıl diziye de değişiklik yansır. Bunun olmaması için ;

In [75]:
anotherCopyArray = anotherArray.copy()

In [76]:
anotherCopyArray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [77]:
anotherArray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [78]:
anotherCopyArraySlicing = anotherCopyArray[3:6]

In [79]:
anotherCopyArraySlicing

array([  3, 700, 700])

In [80]:
anotherCopyArraySlicing[:] = 800

In [81]:
anotherCopyArraySlicing

array([800, 800, 800])

In [82]:
anotherCopyArray

array([  0,   1,   2, 800, 800, 800, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [83]:
anotherArray

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## Matrix

In [6]:
expList= [[10,20,30],[20,30,40],[40,50,60]]

In [7]:
expMatrixList = np.array(expList)

In [8]:
expMatrixList

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [9]:
expMatrixList[0]

array([10, 20, 30])

In [12]:
expMatrixList[1][2]

40

In [13]:
expMatrixList[1,2]

40

In [14]:
expMatrixList[2:,1:]

array([[50, 60]])

In [15]:
newList=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [16]:
newMatrix= np.array(newList)

In [17]:
newMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
newMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operations

In [2]:
randList = np.random.randint(1,100,20)

In [3]:
randList

array([31, 32, 88, 31, 12, 44, 86, 60, 93, 23, 52, 89,  5, 51, 42, 44, 40,
       54, 33, 60])

In [4]:
randList > 24

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
resultArray = randList > 24

In [6]:
randList[resultArray]

array([31, 32, 88, 31, 44, 86, 60, 93, 52, 89, 51, 42, 44, 40, 54, 33, 60])

In [7]:
randList[randList >24]

array([31, 32, 88, 31, 44, 86, 60, 93, 52, 89, 51, 42, 44, 40, 54, 33, 60])

In [8]:
lastArray = np.arange(0,24)

In [9]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [11]:
lastArray * lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [13]:
lastArray / lastArray

C:\Users\senaa\AppData\Local\Temp\ipykernel_13252\206178132.py:1: RuntimeWarning: invalid value encountered in divide
  lastArray / lastArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.sqrt(lastArray) #karekök

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [1]:
if

SyntaxError: invalid syntax (4110802630.py, line 1)